// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using To_Do_List.Models;

#nullable disable

namespace To_Do_List.Migrations
{
    [DbContext(typeof(ToDoListContext))]
    [Migration("20260820072306_initail-fix")]
    partial class initailfix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("To_Do_List.Models.TblCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Category_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Category_Name");

                    b.Property<string>("User")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("CategoryId")
                        .HasName("PK__tbl_Cate__6DB38D6EA1CFE59F");

                    b.HasIndex("User");

                    b.ToTable("tbl_Category", (string)null);
                });

            modelBuilder.Entity("To_Do_List.Models.TblTask", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Task_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<DateOnly?>("CompletedDate")
                        .HasColumnType("date")
                        .HasColumnName("Completed_Date");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TaskCategory")
                        .HasColumnType("int")
                        .HasColumnName("Task_Category");

                    b.Property<DateOnly?>("TaskDate")
                        .HasColumnType("date")
                        .HasColumnName("Task_Date");

                    b.Property<string>("TaskDiscription")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Task_Discription");

                    b.Property<TimeOnly>("TaskTime")
                        .HasColumnType("time")
                        .HasColumnName("Task_Time");

                    b.Property<string>("TaskTitle")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Task_Title");

                    b.Property<string>("TaskUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Task_User");

                    b.HasKey("TaskId")
                        .HasName("PK__tbl_Task__716F4AED2479F05D");

                    b.HasIndex("TaskCategory");

                    b.HasIndex("TaskUser");

                    b.ToTable("tbl_Tasks", (string)null);
                });

            modelBuilder.Entity("To_Do_List.Models.TblTeam", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("team_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<int>("MembersNum")
                        .HasColumnType("int")
                        .HasColumnName("members_num");

                    b.Property<string>("TeamAdmin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("team_admin");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("team_name");

                    b.HasKey("TeamId")
                        .HasName("PK__tbl_Team__F82DEDBC5DED588A");

                    b.ToTable("tbl_Teams", (string)null);
                });

            modelBuilder.Entity("To_Do_List.Models.TblTeamTask", b =>
                {
                    b.Property<int>("TId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("t_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TId"));

                    b.Property<DateOnly>("TCompletedDate")
                        .HasColumnType("date")
                        .HasColumnName("t_CompletedDate");

                    b.Property<DateOnly>("TDate")
                        .HasColumnType("date")
                        .HasColumnName("t_Date");

                    b.Property<string>("TDiscription")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("t_discription");

                    b.Property<string>("TStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("t_status");

                    b.Property<TimeOnly>("TTime")
                        .HasColumnType("time")
                        .HasColumnName("t_Time");

                    b.Property<string>("TTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("t_title");

                    b.HasKey("TId")
                        .HasName("PK__tbl_Team__E579775F4F98DA08");

                    b.ToTable("tbl_TeamTasks", (string)null);
                });

            modelBuilder.Entity("To_Do_List.Models.TblUser", b =>
                {
                    b.Property<string>("UserEmail")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("User_Email");

                    b.Property<string>("ConfirmPassword")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Confirm_Password");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("User_Name");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("User_Password");

                    b.Property<int?>("UserPhone")
                        .HasColumnType("int")
                        .HasColumnName("User_Phone");

                    b.HasKey("UserEmail");

                    b.ToTable("tbl_User", null, t =>
                        {
                            t.HasTrigger("trigger_DeleteUserCategory");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("To_Do_List.Models.TblCategory", b =>
                {
                    b.HasOne("To_Do_List.Models.TblUser", "UserNavigation")
                        .WithMany("TblCategories")
                        .HasForeignKey("User")
                        .HasConstraintName("fk_Category_User");

                    b.Navigation("UserNavigation");
                });

            modelBuilder.Entity("To_Do_List.Models.TblTask", b =>
                {
                    b.HasOne("To_Do_List.Models.TblCategory", "TaskCategoryNavigation")
                        .WithMany("TblTasks")
                        .HasForeignKey("TaskCategory")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_Task_Category");

                    b.HasOne("To_Do_List.Models.TblUser", "TaskUserNavigation")
                        .WithMany("TblTasks")
                        .HasForeignKey("TaskUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_Task_User");

                    b.Navigation("TaskCategoryNavigation");

                    b.Navigation("TaskUserNavigation");
                });

            modelBuilder.Entity("To_Do_List.Models.TblCategory", b =>
                {
                    b.Navigation("TblTasks");
                });

            modelBuilder.Entity("To_Do_List.Models.TblUser", b =>
                {
                    b.Navigation("TblCategories");

                    b.Navigation("TblTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
